include $(GOROOT)/src/Make.inc

TARG=github.com/matryer/gae-records/gaerecords
GOFILES=\
  doc.go \
  errors.go \
  events.go \
  appengine_context.go \
  validators.go \
  record.go \
  paging_info.go \
  model.go

include $(GOROOT)/src/Make.pkg
